num = int(input("chacere pirveli ricxvi: "))
num1 = int(input("chacere meore ricxvi: "))
print(num + num1)
print(num - num1)
print(num * num1)
print(num / num1)
print(num // num1)
print(num ** num1)
print(num % num1)